[workspace]
name = "fjrodl_pddl_course_jazzy_pixi"
channels = ["https://prefix.dev/robostack-jazzy", "https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-64"]
version = "0.1.1"

[dependencies]
# Base ROS dependencies
ros-jazzy-ros-base = "*"
pkg-config = "*"
compilers = "*"
make = "*"
ninja = "*"
ros-jazzy-ros2cli = "*"

# Build tools
colcon-common-extensions = "*"
# version closest to Jazzy
cmake = "3.28.*"

# should this be Linux only?
ccache = "*"

# Workspace dependencies
ros-jazzy-action-msgs = "*"
ros-jazzy-ament-cmake = "*"
ros-jazzy-ament-lint-common = "*"
ros-jazzy-builtin-interfaces = "*"
ros-jazzy-cartographer-ros = "*"
ros-jazzy-dynamixel-sdk = "*"
ros-jazzy-geometry-msgs = "*"
ros-jazzy-hardware-interface = "*"
ros-jazzy-hls-lfcd-lds-driver = "*"
ros-jazzy-joint-state-publisher = "*"
ros-jazzy-joint-state-publisher-gui = "*"
ros-jazzy-nav-msgs = "*"
ros-jazzy-navigation2 = "*"
ros-jazzy-pluginlib = "*"
ros-jazzy-rclcpp = "*"
ros-jazzy-rclpy = "*"
ros-jazzy-robot-state-publisher = "*"
ros-jazzy-ros-gz-bridge = "*"
ros-jazzy-ros-gz-image = "*"
ros-jazzy-ros-gz-sim = "*"
ros-jazzy-ros2-control = "*"
ros-jazzy-ros2-controllers = "*"
ros-jazzy-rosidl-default-generators = "*"
ros-jazzy-rosidl-default-runtime = "*"
ros-jazzy-rviz2 = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-slam-toolbox = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-tf-transformations = "*"
ros-jazzy-tf2 = "*"
ros-jazzy-tf2-msgs = "*"
ros-jazzy-visualization-msgs = "*"
ros-jazzy-xacro = "*"

# from https://github.com/fjrodl/PDDL-course/blob/7c3b5e9b8bab19a1bf608876de2ead7551a6984f/Scripts/jazzy_dependencies_installation.sh#L30
ros-jazzy-nav2-msgs = "*"
ros-jazzy-nav2-costmap-2d = "*"
ros-jazzy-nav2-map-server = "*"
ros-jazzy-nav2-bt-navigator = "*"
ros-jazzy-nav2-bringup = "*"
ros-jazzy-interactive-marker-twist-server = "*"


# from: https://github.com/fjrodl/PDDL-course/blob/7c3b5e9b8bab19a1bf608876de2ead7551a6984f/Scripts/day3_jazzy.sh
ros-jazzy-turtlebot3 = "*"
ros-jazzy-turtlebot3-bringup = "*"
ros-jazzy-turtlebot3-cartographer = "*"
ros-jazzy-turtlebot3-description = "*"
ros-jazzy-turtlebot3-example = "*"
ros-jazzy-turtlebot3-fake-node = "*"
ros-jazzy-turtlebot3-gazebo = "*"
ros-jazzy-turtlebot3-msgs = "*"
ros-jazzy-turtlebot3-navigation2 = "*"
ros-jazzy-turtlebot3-node = "*"
ros-jazzy-turtlebot3-simulations = "*"
ros-jazzy-turtlebot3-teleop = "*"



[target.linux-64.dependencies]
# from https://github.com/fjrodl/PDDL-course/blob/7c3b5e9b8bab19a1bf608876de2ead7551a6984f/Scripts/jazzy_dependencies_installation.sh#L47
# other platforms will unfortunately have to build plansys from source
ros-jazzy-plansys2-bringup = "*"
ros-jazzy-plansys2-bt-actions = "*"
ros-jazzy-plansys2-core = "*"
ros-jazzy-plansys2-domain-expert = "*"
ros-jazzy-plansys2-executor = "*"
ros-jazzy-plansys2-lifecycle-manager = "*"
ros-jazzy-plansys2-msgs = "*"
ros-jazzy-plansys2-pddl-parser = "*"
ros-jazzy-plansys2-planner = "*"
ros-jazzy-plansys2-popf-plan-solver = "*"
ros-jazzy-plansys2-problem-expert = "*"
ros-jazzy-plansys2-support-py = "*"
ros-jazzy-plansys2-terminal = "*"
ros-jazzy-plansys2-tests = "*"
ros-jazzy-plansys2-tools = "*"


[target.osx-64.dependencies]
# for popf (linux-64 can depend on a binary)
bison = "*"
coin-or-cbc = "*"
coin-or-cgl = "*"
flex = "*"

# plansys dependencies
eigen = "*"
pytest = "*"
qt-main = "*"
readline = "*"
xorg-libx11 = "*"
xorg-libxext = "*"
# plansys ROS dependencies
ros-jazzy-ament-cmake-gtest = "*"
ros-jazzy-ament-copyright = "*"
ros-jazzy-ament-flake8 = "*"
ros-jazzy-ament-index-cpp = "*"
ros-jazzy-ament-lint-auto = "*"
ros-jazzy-ament-pep257 = "*"
ros-jazzy-behaviortree-cpp = "*"
ros-jazzy-eigen3-cmake-module = "*"
#ros-jazzy-popf = "*"  # will be built from source
ros-jazzy-python-cmake-module = "*"
ros-jazzy-qt-gui-cpp = "*"
ros-jazzy-rclcpp-action = "*"
ros-jazzy-rclcpp-cascade-lifecycle = "*"
ros-jazzy-rclcpp-lifecycle = "*"
ros-jazzy-ros2run = "*"
ros-jazzy-rqt-gui = "*"
ros-jazzy-rqt-gui-cpp = "*"
ros-jazzy-std-srvs = "*"
ros-jazzy-test-msgs = "*"


[tasks]
fetch = {cmd = "vcs import --input repos.repos src", description = "Fetch packages"}
fetch_osx64 = {cmd = "vcs import --input repos-osx-64.repos src", description = "Fetch packages (for macOS)"}
build = {cmd = "colcon build", description = "Build the ROS workspace"}
ws-clean = {cmd = "rm -rf build install log", description = "Clean build artifacts (build, install, log directories)"}
clean-build = [{ task = "ws-clean" }, { task = "build" }]

[activation]
#scripts = ["install/setup.bash"]

[pypi-dependencies]
vcstool = ">=0.3.0, <0.4"

[activation.env]
ROS_AUTOMATIC_DISCOVERY_RANGE = "LOCALHOST"
# TODO: make these Linux only?
CMAKE_CXX_COMPILER_LAUNCHER = "ccache"
CMAKE_C_COMPILER_LAUNCHER = "ccache"
